name: Linux Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: 20.2.0.java11
    - name: Install libraries
      run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
    - name: Make staging directory
      run: mkdir staging
#    - name: setup android certs
#      run: |
#          mkdir /home/runner/.gluon
#          printf "${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}" > keystore.base64
#          base64 -d keystore.base64 > /home/runner/my.keystore
#          ls -l /home/runner/my.keystore
    - name: Gluon Build
      uses: erwin1/gluon-build@main
      with:
        gluon-license: ${{ secrets.GLUON_LICENSE }}
        target: 'android'
        GLUON_ANDROID_KEYSTORE_BASE64: ${{ secrets.GLUON_ANDROID_KEYSTORE_BASE64 }}
        GLUON_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYSTORE_PASSWORD }}
        GLUON_ANDROID_KEYALIAS: ${{ secrets.GLUON_ANDROID_KEYALIAS }}
        GLUON_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.GLUON_ANDROID_KEYALIAS_PASSWORD }}
    - name: Copy native clients to staging
      run: cp -r target/client/aarch64-android/gvm/*.apk staging
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
